---
title: "Intro to using Esquisse"
output: html_notebook
---


# Run this first chunk of code to install packages before class
```{r}
#this will check to ensure you have the right packages installed and will install them if necessary
packages <- c("tidyverse", "janitor",  "esquisse", "lubridate")
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())), repos = "http://cran.us.r-project.org")  
}
```




```{r}

library(tidyverse)
library(janitor)
library(esquisse)
library(lubridate)


#import data on people killed by police, from the Washington Post

fatal_df <-  read_csv('https://raw.githubusercontent.com/washingtonpost/data-police-shootings/master/fatal-police-shootings-data.csv') %>% clean_names() %>% 
  mutate(yr = as.character(year(date)),
         yr_numeric = as.numeric(year(date)))


```



# Esquisse

This package allows us to launch an interface to build a visualization by pushing buttons instead of writing code. 

It has limitations, which you'll see in a minute, but is a place to start

```{r}

#this function -- esquisser() -- launches the interface
# you just have to tell it what data frame to use

esquisse::esquisser(fatal_df)




```



# Deaths by year, by race


```{r}

byrace <- fatal_df %>% filter(race!='NA') %>%  group_by(yr, yr_numeric, race) %>% summarize(count = n())






```


```{r}


esquisse::esquisser(byrace)
```



